### ISSUE TITLE
No chapter/video tags

### ISSUE THREAD

**Issue by motenko** [PacktPublishing/Hands-on-Web-Development-with-React#2]
In section 2, video 1:  Building Components with React, Creating a Reusable List Component at 00:45 time, it says that the source code on GitHub would have tags for each video so we could follow along. Please help me to find and view the tags in GitHub. I've included a screenshot indicating that GitHub has no tags listed. Are the tags somewhere else? 

When I try to follow along, I have to delete the code from the master branch and then guess what I should include for each specific video. This is very frustrating. Thanks for your help. 

![screen shot 2018-12-23 at 1 46 02 am](https://user-images.githubusercontent.com/1467164/50381475-102f4c00-0656-11e9-8037-d3e7ffbf3607.png)

**Comment by filipdanic** [comment]
Hey @motenko, sorry for not responding sooner, your email ended up in my spam folder. I’m sorry to hear you’ve experienced problems with this, but I hopefully have a solution that will work for you.

Instead of looking for the tags, switch over to the history view. Here’s the link https://github.com/PacktPublishing/Hands-on-Web-Development-with-React/commits/master

There you can switch to that commit or view the diff by clicking on the buttons next to each commit,

E.g. the commit _Add code for section 3 video “Functional (Stateless) Components“_ has the following diff:
https://github.com/PacktPublishing/Hands-on-Web-Development-with-React/commit/adeddfaecb35780b49f3f20aaa2641e01a0ccd1e

If you clone the repository and open it using something like the GitHub Desktop client, you can also easily navigate the history and (1) switch between revisions and (2) see diffs between videos.
<img width="1440" alt="screen shot 2019-01-06 at 3 10 19 am" src="https://user-images.githubusercontent.com/7009755/50731275-c3249d00-1160-11e9-915f-7e7208e02212.png">
